FROM golang
RUN go get -v github.com/TaKeO90/fillpdf
WORKDIR /go/src/github.com/TaKeO90/fillpdf
RUN CGO_ENABLED=0 GOOS=linux go build -a --installsuffix cgo -o app .

FROM iron/base
RUN apk update; apk add pdftk
WORKDIR /root
COPY --from=0 /go/src/github.com/TaKeO90/fillpdf/app .
CMD ["./app"]
